[package]
name = "rna-ss-params"
version = "0.1.6"
authors = ["heartsh <heartsh@heartsh.io>"]
description = "RNA secondary-structure parameters"
repository = "https://github.com/heartsh/rna-ss-prms"
readme = "README.md"
keywords = ["bioinformatics", "rna", "secondary-structure"]
license = "MIT"

[dependencies]
fnv = "1.0"
lazy_static = "0.1"

[lib]
path = "src/lib.rs"
name = "rna_ss_params"
