/* use utils::*;

pub const MISMATCH_STACK_DELTA_FE_WHERE_BACKBONE_IS_NOT_CONTINUOUS: FreeEnergy = - INVERSE_TEMPERATURE * (-2.1);
pub const WATSON_CRICK_MISMATCH_BONUS_DELTA_FE: FreeEnergy = - INVERSE_TEMPERATURE * -0.4;
pub const GU_MISMATCH_BONUS_DELTA_FE: FreeEnergy = - INVERSE_TEMPERATURE * -0.2; */
