use utils::*;

pub const MISMATCH_STACK_DELTA_FE_WHERE_BACKBONE_IS_NOT_CONTINUOUS: FreeEnergy = - INVERSE_TEMPERATURE * -2.1;
pub const WATSON_CRICK_MISMATCH_BONUS_DELTA_FE: FreeEnergy = - INVERSE_TEMPERATURE * -0.4;
pub const GU_MISMATCH_BONUS_DELTA_FE: FreeEnergy = - INVERSE_TEMPERATURE * -0.2;
lazy_static! {
  pub static ref EXP_MISMATCH_STACK_DELTA_FE_WHERE_BACKBONE_IS_NOT_CONTINUOUS: FreeEnergy = MISMATCH_STACK_DELTA_FE_WHERE_BACKBONE_IS_NOT_CONTINUOUS.exp();
  pub static ref EXP_WATSON_CRICK_MISMATCH_BONUS_DELTA_FE: FreeEnergy = WATSON_CRICK_MISMATCH_BONUS_DELTA_FE.exp();
  pub static ref EXP_GU_MISMATCH_BONUS_DELTA_FE: FreeEnergy = GU_MISMATCH_BONUS_DELTA_FE.exp();
}
