use utils::*;

pub const CONST_4_ML: FreeEnergy = 9.25;
pub const COEFFICENT_4_AVERAGE_ASYMMETRY: FreeEnergy = 0.91;
pub const COEFFICENT_4_NUM_OF_BRANCHING_HELICES: FreeEnergy = -0.63;
pub const BONUS_DELTA_FE_4_STRAIN_BY_3_WAY_BRANCHING_LOOPS_WITH_FEWER_THAN_2_UNPAIRED_BASES: FreeEnergy = 3.14;
