use utils::*;

pub const CONST_4_INIT_ML_DELTA_FE: FreeEnergy = - INVERSE_TEMPERATURE * 9.25;
pub const COEFFICIENT_4_AVERAGE_ASYMMETRY_TERM_ON_INIT_ML_DELTA_FE: FreeEnergy = - INVERSE_TEMPERATURE * 0.91;
pub const COEFFICIENT_4_TERM_OF_NUM_OF_BRANCHING_HELICES_ON_INIT_ML_DELTA_FE: FreeEnergy = - INVERSE_TEMPERATURE * (-0.63);
pub const BONUS_DELTA_FE_4_STRAIN_BY_ML_3_WAY_BRANCHING_LOOPS_WITH_FEWER_THAN_2_UNPAIRED_BASES: FreeEnergy = - INVERSE_TEMPERATURE * 3.14;
