name: CI

on:
  push:
    branches:
      - dev
      - release
      - "feature/**"

jobs:
  preinstall:
    name: Pre-install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pre-install
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

  verify:
    name: Verify
    runs-on: ubuntu-latest
    needs: preinstall
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: |
          cargo install --path . -q
      - name: Execute binaries
        run: |
          ./generate_scores.sh
        working-directory: ./scripts
      - name: Check packaging
        run: |
          cargo package -q

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    needs: preinstall
    steps:
      - uses: actions/checkout@v3
      - name: Check format
        run: |
          rustup component add rustfmt
          cargo fmt --check
      - name: Lint
        run: |
          rustup component add clippy
          cargo clippy -q
